/* Application Router  generated by JSetup v0.95 :  at 01/12/2019 12:41:14 */
import React from 'react';
import { HashRouter as Router, Route, Switch } from 'react-router-dom';

import FormActor from '../components/actor/FormActor'
import PageActor from '../components/actor/PageActor'
import FormMaturityRating from '../components/maturityRating/FormMaturityRating'
import PageMaturityRating from '../components/maturityRating/PageMaturityRating'
import FormMovie from '../components/movie/FormMovie'
import PageMovie from '../components/movie/PageMovie'
import FormCustomer from '../components/customer/FormCustomer'
import PageCustomer from '../components/customer/PageCustomer'
import FormProfile from '../components/profile/FormProfile'
import PageProfile from '../components/profile/PageProfile'
import FormSuggestion from '../components/suggestion/FormSuggestion'
import PageSuggestion from '../components/suggestion/PageSuggestion'
import FormGenre from '../components/genre/FormGenre'
import PageGenre from '../components/genre/PageGenre'
import FormUser from '../components/user/FormUser'
import PageUser from '../components/user/PageUser'
import FormRole from '../components/role/FormRole'
import PageRole from '../components/role/PageRole'
import FormPermission from '../components/permission/FormPermission'
import PagePermission from '../components/permission/PagePermission'
import FormGroup from '../components/group/FormGroup'
import PageGroup from '../components/group/PageGroup'
import FormItem from '../components/item/FormItem'
import PageItem from '../components/item/PageItem'

const Root = () => {
  return (
    <Router>
      <div>
         <Route path="/actors/edit/:id" component={FormActor} exact />
         <Route path="/actors/new" component={FormActor} exact />
         <Route path="/actors/list" component={PageActor} exact />
         <Route path="/maturityRatings/edit/:id" component={FormMaturityRating} exact />
         <Route path="/maturityRatings/new" component={FormMaturityRating} exact />
         <Route path="/maturityRatings/list" component={PageMaturityRating} exact />
         <Route path="/movies/edit/:id" component={FormMovie} exact />
         <Route path="/movies/new" component={FormMovie} exact />
         <Route path="/movies/list" component={PageMovie} exact />
         <Route path="/customers/edit/:id" component={FormCustomer} exact />
         <Route path="/customers/new" component={FormCustomer} exact />
         <Route path="/customers/list" component={PageCustomer} exact />
         <Route path="/profiles/edit/:id" component={FormProfile} exact />
         <Route path="/profiles/new" component={FormProfile} exact />
         <Route path="/profiles/list" component={PageProfile} exact />
         <Route path="/suggestions/edit/:id" component={FormSuggestion} exact />
         <Route path="/suggestions/new" component={FormSuggestion} exact />
         <Route path="/suggestions/list" component={PageSuggestion} exact />
         <Route path="/genres/edit/:id" component={FormGenre} exact />
         <Route path="/genres/new" component={FormGenre} exact />
         <Route path="/genres/list" component={PageGenre} exact />
         <Route path="/users/edit/:id" component={FormUser} exact />
         <Route path="/users/new" component={FormUser} exact />
         <Route path="/users/list" component={PageUser} exact />
         <Route path="/roles/edit/:id" component={FormRole} exact />
         <Route path="/roles/new" component={FormRole} exact />
         <Route path="/roles/list" component={PageRole} exact />
         <Route path="/permissions/edit/:id" component={FormPermission} exact />
         <Route path="/permissions/new" component={FormPermission} exact />
         <Route path="/permissions/list" component={PagePermission} exact />
         <Route path="/groups/edit/:id" component={FormGroup} exact />
         <Route path="/groups/new" component={FormGroup} exact />
         <Route path="/groups/list" component={PageGroup} exact />
         <Route path="/items/edit/:id" component={FormItem} exact />
         <Route path="/items/new" component={FormItem} exact />
         <Route path="/items/list" component={PageItem} exact />
      </div>
    </Router>
  );
};

export default Root;

