/* Movie´s Form generated by JSetup v0.95 :  at 01/12/2019 12:41:14 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";

import ModalMaturityRating from "../maturityRating/ModalMaturityRating";

import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyMovie = {
	id: '',
	title: '',    	
	poster: '',    	
	duration: '',    	
	releaseDate: '',    	
	sinopse: '',    	
	director: '',    	
};

export default class FormMovie extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/movies");
        this.serviceGenre = new HttpRequest("/rs/crud/genres");
        
        this.state = {
            movie: emptyMovie,
			genreList: [],
		
            message: new Message(),
            showMessage: false,

            validationFields: {
                title: {
                    isValid: () => {
                        return isNotEmpty(this.state.movie.title);
                    },
                    message: "Campo Obrigatório!",
                },
                releaseDate: {
                    isValid: () => {
                        return isNotEmpty(this.state.movie.releaseDate);
                    },
                    message: "Campo Obrigatório!",
                },
                sinopse: {
                    isValid: () => {
                        return isNotEmpty(this.state.movie.sinopse);
                    },
                    message: "Campo Obrigatório!",
                },
            }
        }
    }
    componentDidMount = () => {
        this.serviceGenre.getAll(
            genreList => {
                this.setState({ genreList  });
            },
            error => {
                console.error("error fetching forr combobox", error);
            }
        );
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.movie);
        this.service.save(
            this.state.movie,
            data => {
                this.movie = data;
				this.setState({ message: new Message("success", "Success saving Movie"), showMessage: true })
                this.setState({ movie: emptyMovie });

            },
            error => {
                console.error("error saving movie ", error);
				this.setState({ message: new Message("danger", "Error saving Movie"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const movie = { ...this.state.movie };
        movie[name] = value;
        this.setState({ movie });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Movie</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="title" validationState={this.getValidationState("title")} >
                                    <ControlLabel>Title</ControlLabel>
                                    <JSInputField name="title" type="text" value={this.state.movie.title}  onChange={(event) => this.changeFormDateHandle("title", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("title") ? "hide" : "block"} >{this.getValidationMessage("title")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="poster" validationState={this.getValidationState("poster")} >
                                    <ControlLabel>Poster</ControlLabel>
                                    <JSInputField name="poster" type="text" value={this.state.movie.poster}  onChange={(event) => this.changeFormDateHandle("poster", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("poster") ? "hide" : "block"} >{this.getValidationMessage("poster")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="duration" validationState={this.getValidationState("duration")} >
                                    <ControlLabel>Duration</ControlLabel>
                                    <JSInputField name="duration" plugin="integer" type="text" value={this.state.movie.duration}  onChange={(event) => this.changeFormDateHandle("duration", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("duration") ? "hide" : "block"} >{this.getValidationMessage("duration")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="releaseDate" validationState={this.getValidationState("releaseDate")} >
                                    <ControlLabel>Release date</ControlLabel>
                                    <JSInputField name="releaseDate" plugin="date" type="text" value={this.state.movie.releaseDate}  onChange={(event) => this.changeFormDateHandle("releaseDate", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("releaseDate") ? "hide" : "block"} >{this.getValidationMessage("releaseDate")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="sinopse" validationState={this.getValidationState("sinopse")} >
                                    <ControlLabel>Sinopse</ControlLabel>
                                    <JSInputField name="sinopse" type="text" value={this.state.movie.sinopse}  onChange={(event) => this.changeFormDateHandle("sinopse", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("sinopse") ? "hide" : "block"} >{this.getValidationMessage("sinopse")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="director" validationState={this.getValidationState("director")} >
                                    <ControlLabel>Director</ControlLabel>
                                    <JSInputField name="director" type="text" value={this.state.movie.director}  onChange={(event) => this.changeFormDateHandle("director", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("director") ? "hide" : "block"} >{this.getValidationMessage("director")}</HelpBlock>
                                </FormGroup>
                                
		                        <FormGroup controlId="titulo" validationState={this.getValidationState("maturityRating")} >
		                            <ControlLabel>MaturityRating</ControlLabel>
		                            <FormControl.Feedback />
									<ModalMaturityRating value={this.state.movie.maturityRating} displayValue="name" idValue="id" onChange={(event) => this.changeFormDateHandle("maturityRating", event.target.value)}  />
		                            <HelpBlock className={this.validateField("maturityRating") ? "hide" : "block"} >{this.getValidationMessage("maturityRating")}</HelpBlock>
		                        </FormGroup>
		                              					
		                        <FormGroup controlId="titulo" validationState={this.getValidationState("genre")} >
		                            <ControlLabel>Genre</ControlLabel>
		                            <FormControl.Feedback />
		                            <JSCombobox value={this.state.movie.genre} values={this.state.genreList} displayValue="name" idValue="id" onChange={(event) => this.changeFormDateHandle("genre", event.target.value)} className="form-control" />
		                            <HelpBlock className={this.validateField("genre") ? "hide" : "block"} >{this.getValidationMessage("genre")}</HelpBlock>
		                        </FormGroup>      	
		                        				
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/movies/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

