/* Actor´s Form generated by JSetup v0.95 :  at 01/12/2019 12:41:14 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";


import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyActor = {
	id: '',
	biography: '',    	
	birthDate: '',    	
	name: '',    	
	picture: '',    	
};

export default class FormActor extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/actors");
        
        this.state = {
            actor: emptyActor,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
                birthDate: {
                    isValid: () => {
                        return isNotEmpty(this.state.actor.birthDate);
                    },
                    message: "Campo Obrigatório!",
                },
                name: {
                    isValid: () => {
                        return isNotEmpty(this.state.actor.name);
                    },
                    message: "Campo Obrigatório!",
                },
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.actor);
        this.service.save(
            this.state.actor,
            data => {
                this.actor = data;
				this.setState({ message: new Message("success", "Success saving Actor"), showMessage: true })
                this.setState({ actor: emptyActor });

            },
            error => {
                console.error("error saving actor ", error);
				this.setState({ message: new Message("danger", "Error saving Actor"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const actor = { ...this.state.actor };
        actor[name] = value;
        this.setState({ actor });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Actor</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="biography" validationState={this.getValidationState("biography")} >
                                    <ControlLabel>Biography</ControlLabel>
                                    <JSInputField name="biography" type="text" value={this.state.actor.biography}  onChange={(event) => this.changeFormDateHandle("biography", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("biography") ? "hide" : "block"} >{this.getValidationMessage("biography")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="birthDate" validationState={this.getValidationState("birthDate")} >
                                    <ControlLabel>Birth date</ControlLabel>
                                    <JSInputField name="birthDate" plugin="date" type="text" value={this.state.actor.birthDate}  onChange={(event) => this.changeFormDateHandle("birthDate", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("birthDate") ? "hide" : "block"} >{this.getValidationMessage("birthDate")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="name" validationState={this.getValidationState("name")} >
                                    <ControlLabel>Name</ControlLabel>
                                    <JSInputField name="name" type="text" value={this.state.actor.name}  onChange={(event) => this.changeFormDateHandle("name", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("name") ? "hide" : "block"} >{this.getValidationMessage("name")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="picture" validationState={this.getValidationState("picture")} >
                                    <ControlLabel>Picture</ControlLabel>
                                    <JSInputField name="picture" type="text" value={this.state.actor.picture}  onChange={(event) => this.changeFormDateHandle("picture", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("picture") ? "hide" : "block"} >{this.getValidationMessage("picture")}</HelpBlock>
                                </FormGroup>
                                
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/actors/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

