/* Customer´s Form generated by JSetup v0.95 :  at 01/12/2019 12:41:14 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";


import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyCustomer = {
	id: '',
	telephone: '',    	
	discount: '',    	
	dueDate: '',    	
	cpf: '',    	
	name: '',    	
	monthlyFee: '',    	
	observation: '',    	
	active: '',    	
	picture: '',    	
	celphone: '',    	
	rg: '',    	
	subscriptionDatetime: '',    	
	birthDate: '',    	
};

export default class FormCustomer extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/customers");
        
        this.state = {
            customer: emptyCustomer,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
                telephone: {
                    isValid: () => {
                        return isNotEmpty(this.state.customer.telephone);
                    },
                    message: "Campo Obrigatório!",
                },
                cpf: {
                    isValid: () => {
                        return isNotEmpty(this.state.customer.cpf);
                    },
                    message: "Campo Obrigatório!",
                },
                name: {
                    isValid: () => {
                        return isNotEmpty(this.state.customer.name);
                    },
                    message: "Campo Obrigatório!",
                },
                rg: {
                    isValid: () => {
                        return isNotEmpty(this.state.customer.rg);
                    },
                    message: "Campo Obrigatório!",
                },
                subscriptionDatetime: {
                    isValid: () => {
                        return isNotEmpty(this.state.customer.subscriptionDatetime);
                    },
                    message: "Campo Obrigatório!",
                },
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.customer);
        this.service.save(
            this.state.customer,
            data => {
                this.customer = data;
				this.setState({ message: new Message("success", "Success saving Customer"), showMessage: true })
                this.setState({ customer: emptyCustomer });

            },
            error => {
                console.error("error saving customer ", error);
				this.setState({ message: new Message("danger", "Error saving Customer"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const customer = { ...this.state.customer };
        customer[name] = value;
        this.setState({ customer });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Customer</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="telephone" validationState={this.getValidationState("telephone")} >
                                    <ControlLabel>Telephone</ControlLabel>
                                    <JSInputField name="telephone" type="text" value={this.state.customer.telephone}  onChange={(event) => this.changeFormDateHandle("telephone", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("telephone") ? "hide" : "block"} >{this.getValidationMessage("telephone")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="discount" validationState={this.getValidationState("discount")} >
                                    <ControlLabel>Discount</ControlLabel>
                                    <JSInputField name="discount" plugin="decimal" type="text" value={this.state.customer.discount}  onChange={(event) => this.changeFormDateHandle("discount", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("discount") ? "hide" : "block"} >{this.getValidationMessage("discount")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="dueDate" validationState={this.getValidationState("dueDate")} >
                                    <ControlLabel>Due date</ControlLabel>
                                    <JSInputField name="dueDate" plugin="date" type="text" value={this.state.customer.dueDate}  onChange={(event) => this.changeFormDateHandle("dueDate", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("dueDate") ? "hide" : "block"} >{this.getValidationMessage("dueDate")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="cpf" validationState={this.getValidationState("cpf")} >
                                    <ControlLabel>Cpf</ControlLabel>
                                    <JSInputField name="cpf" type="text" value={this.state.customer.cpf}  onChange={(event) => this.changeFormDateHandle("cpf", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("cpf") ? "hide" : "block"} >{this.getValidationMessage("cpf")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="name" validationState={this.getValidationState("name")} >
                                    <ControlLabel>Name</ControlLabel>
                                    <JSInputField name="name" type="text" value={this.state.customer.name}  onChange={(event) => this.changeFormDateHandle("name", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("name") ? "hide" : "block"} >{this.getValidationMessage("name")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="monthlyFee" validationState={this.getValidationState("monthlyFee")} >
                                    <ControlLabel>Monthly fee</ControlLabel>
                                    <JSInputField name="monthlyFee" plugin="decimal" type="text" value={this.state.customer.monthlyFee}  onChange={(event) => this.changeFormDateHandle("monthlyFee", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("monthlyFee") ? "hide" : "block"} >{this.getValidationMessage("monthlyFee")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="observation" validationState={this.getValidationState("observation")} >
                                    <ControlLabel>Observation</ControlLabel>
                                    <JSInputField name="observation" type="text" value={this.state.customer.observation}  onChange={(event) => this.changeFormDateHandle("observation", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("observation") ? "hide" : "block"} >{this.getValidationMessage("observation")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="active" validationState={this.getValidationState("active")} >
                                    <ControlLabel>Active</ControlLabel>
                                    <JSInputField name="active" type="text" value={this.state.customer.active}  onChange={(event) => this.changeFormDateHandle("active", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("active") ? "hide" : "block"} >{this.getValidationMessage("active")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="picture" validationState={this.getValidationState("picture")} >
                                    <ControlLabel>Picture</ControlLabel>
                                    <JSInputField name="picture" type="text" value={this.state.customer.picture}  onChange={(event) => this.changeFormDateHandle("picture", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("picture") ? "hide" : "block"} >{this.getValidationMessage("picture")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="celphone" validationState={this.getValidationState("celphone")} >
                                    <ControlLabel>Celphone</ControlLabel>
                                    <JSInputField name="celphone" type="text" value={this.state.customer.celphone}  onChange={(event) => this.changeFormDateHandle("celphone", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("celphone") ? "hide" : "block"} >{this.getValidationMessage("celphone")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="rg" validationState={this.getValidationState("rg")} >
                                    <ControlLabel>Rg</ControlLabel>
                                    <JSInputField name="rg" type="text" value={this.state.customer.rg}  onChange={(event) => this.changeFormDateHandle("rg", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("rg") ? "hide" : "block"} >{this.getValidationMessage("rg")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="subscriptionDatetime" validationState={this.getValidationState("subscriptionDatetime")} >
                                    <ControlLabel>Subscription datetime</ControlLabel>
                                    <JSInputField name="subscriptionDatetime" plugin="datetime" type="text" value={this.state.customer.subscriptionDatetime}  onChange={(event) => this.changeFormDateHandle("subscriptionDatetime", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("subscriptionDatetime") ? "hide" : "block"} >{this.getValidationMessage("subscriptionDatetime")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="birthDate" validationState={this.getValidationState("birthDate")} >
                                    <ControlLabel>Birth date</ControlLabel>
                                    <JSInputField name="birthDate" plugin="date" type="text" value={this.state.customer.birthDate}  onChange={(event) => this.changeFormDateHandle("birthDate", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("birthDate") ? "hide" : "block"} >{this.getValidationMessage("birthDate")}</HelpBlock>
                                </FormGroup>
                                
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/customers/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

